export const emptyInputData = {
  firstName: "",
  middleName: "",
  lastName: "",
  fatherName: "",
  nationality: "",
  domicile: "",
  dateOfBirth: "",
  gender: "",
  email: "",
  phone: "",
  programName: "",
  programCode: "",
  address: "",
  sourceOfInformation: "",
  qualification: "",
  acedemicSession: "",
  photo: "",
  lastInstituteName: "",
  lastBoardCollege: "",
  yearOfPassing: "",
  stream: "",
  marks: "",
};

export const feeEmptyInputData = {
  firstName: "",
  middleName: "",
  lastName: "",
  address: "",
  feeAmount: "",
  feeAmountInWords: "",
};
